name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["e-chan1007/github-profile-summary-cards@main"]'
          checkout_base_path: ./.github/actions
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Using custom private action 1'
        uses: ./.github/actions/github-profile-summary-cards
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
