name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
        with:
          repository: e-chan1007/github-profile-summary-cards
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - run: npm run run e-chan1007
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
