name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 12 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.languages.svg
          base: ""
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_languages_ignored: >-
            tex, dockerfile, jupyter notebook, markdown, mdx,
            makefile, shell, powershell, gnuplot, bibtex, bibtex style
